#!/usr/bin/env bash
# Install nginx and display string
apt-get update
apt-get install nginx -y
echo 'Hello World!' > sudo tee /var/www/html/index.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default 
sudo service nginx start
