#!/usr/bin/env bash
# Install nginx and display string
sudo apt-get update
sudo apt-get install nginx -y
sudo vi /var/www/html/index.html
#insert Hello World into new file
sudo sed -i 'server {/a location /redirect_me { rewrite ^/redirect_me$
 https://github.com/speck249 permanent; }' /etc/nginx/sites-available/default
service nginx start
