#!/usr/bin/env bash
# Install nginx and display string
apt-get update
apt-get install nginx -y
echo "Hello World!" > sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" > sudo tee /var/www/html/404.html
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
        error_page 404 = /404;
        location = /404 {
           internal;
           root /var/www/html;
           try_files $uri /404.html
        }
}" > /etc/nginx/sites-available/default 
sudo service nginx start
