#!/usr/bin/env bash
# Install nginx and display string
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
# Insert string into new html file.
echo "Hello World!" | sudo tee /var/www/html/index.html
# Create custom redirect page.
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}" > /etc/nginx/sites-enabled/default
# Insert string into custom error page.
echo "Ceci n'est pas une page" | sudo tee /var/www/html/my_404.html
# Configure error page.
sudo sed -i 's@listen 80 default_server;@listen 80 default_server;\n\terror_page 404 /my_404.html;\n\tlocation = /my_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}@' /etc/nginx/sites-enabled/default

#Create and implement custom HTTP header
echo "http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;
        gzip on;
        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
        add_header X-Served-By $hostname;
}" > /etc/nginx/nginx.conf

#Start nginx
sudo service nginx restart
