#!/usr/bin/env bash
#displays 1 - 20

s=1

while [ $s -le 20 ];
do
  echo "$s"

  case $s in
      4)
	 echo -n "bad luck from China"
         ;;

      9)
         echo "bad luck from Japan"
         ;;

      17)
         echo "bad luck from Italy"
         ;;
  esac
  ((s++))
done
